FROM node:18-alpine

RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app
COPY . .
ARG MONGODB_URI
ARG NAME
ARG SECRET
ARG PUBLIC_SITE_URL
ARG NEXTAUTH_URL
ARG smtpHost
ARG smtpPort
ARG smtpUser
ARG smtpPass
ARG privateKey
ARG BOT_TOKEN
ARG BOT_ID
ARG BOT_LOGIN
ARG PORT
ARG NUXT_HOST
ARG NUXT_PORT
ARG fkApiKey
ARG fkSecret1
ARG fkSecret2
ARG fkID
ARG YANDEX_SECRET_KEY
ARG YANDEX_ACCESS_KEY_ID
ARG WB_DB_URI
ARG OZON_DB_URI
ARG VK_SECRET_KEY
ARG VK_ACCESS_KEY
ARG IMAGES_URL
ARG YANDEX_MAPS_API_KEY
ARG AVITO_DB_URI
ARG YANDEX_MARKET_DB_URI
ARG OZON_HOTELS_DB_URI
ARG SUTOCHNO_DB_URI
ARG FLOWWOW_DB_URI
ARG OZON_PVZ_DB_URI
ARG GOLD_APPLE_DB_URI

ENV MONGODB_URI=${MONGODB_URI}
ENV NAME=${NAME}
ENV SECRET=${SECRET}
ENV PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV smtpHost=${smtpHost}
ENV smtpPort=${smtpPort}
ENV smtpUser=${smtpUser}
ENV smtpPass=${smtpPass}
ENV privateKey=${privateKey}
ENV BOT_TOKEN=${BOT_TOKEN}
ENV BOT_ID=${BOT_ID}
ENV BOT_LOGIN=${BOT_LOGIN}
ENV PORT=${PORT}
ENV NUXT_HOST=${NUXT_HOST}
ENV NUXT_PORT=${NUXT_PORT}
ENV fkApiKey=${fkApiKey}
ENV fkSecret1=${fkSecret1}
ENV fkSecret2=${fkSecret2}
ENV fkID=${fkID}
ENV YANDEX_SECRET_KEY=${YANDEX_SECRET_KEY}
ENV YANDEX_ACCESS_KEY_ID=${YANDEX_ACCESS_KEY_ID}
ENV WB_DB_URI=${WB_DB_URI}
ENV OZON_DB_URI=${OZON_DB_URI}
ENV VK_SECRET_KEY=${VK_SECRET_KEY}
ENV VK_ACCESS_KEY=${VK_ACCESS_KEY}
ENV IMAGES_URL=${IMAGES_URL}
ENV YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY}
ENV AVITO_DB_URI=${AVITO_DB_URI}
ENV YANDEX_MARKET_DB_URI=${YANDEX_MARKET_DB_URI}
ENV OZON_HOTELS_DB_URI=${OZON_HOTELS_DB_URI}
ENV SUTOCHNO_DB_URI=${SUTOCHNO_DB_URI}
ENV FLOWWOW_DB_URI=${FLOWWOW_DB_URI}
ENV OZON_PVZ_DB_URI=${OZON_PVZ_DB_URI}
ENV GOLD_APPLE_DB_URI=${GOLD_APPLE_DB_URI}

RUN npm install -g pnpm
RUN apk add --no-cache python3 make g++
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN pnpm install
RUN pnpm run build
ENV NODE_ENV production
ENV PORT 5000

EXPOSE 5000

ENTRYPOINT ["node", "--max-old-space-size=4096", ".output/server/index.mjs"]
