import { Schema, model } from "mongoose";
const BuyoutSchema = new Schema({
	searchquery: { type: String, unique: false, required: true, text: true },
	sizeparam: { type: String, unique: false, required: true, text: true },
	quantity: { type: Number, unique: false, required: true, text: true },
	gender: { type: String, unique: false, required: true, text: true },
	article: { type: Number, unique: false, required: true, text: true },
	point: { type: String, unique: false, required: true, text: true },
	dateStart: { type: Date, default: Date.now },
	dateEnd: { type: Date, default: Date.now },
	orderPaymentDate: { type: Date, default: Date.now },
	orderPaymentStatus: {
		type: String,
		unique: false,
		required: true,
		text: true,
	},
	orderPaymentLink: { type: String, unique: false, required: true, text: true },
	servicePaymentDate: { type: Date, default: Date.now },
	servicePaymentStatus: {
		type: String,
		unique: false,
		required: true,
		text: true,
	},
	servicePaymentLink: {
		type: String,
		unique: false,
		required: true,
		text: true,
	},
	rules: { type: Array, unique: false, required: true, text: true },
	status: { type: String, unique: false, required: true, text: true },
	user: { type: Schema.Types.ObjectId, ref: "User" },
	data5: { unique: false, required: true, text: true, default: "" },
	data6: { unique: false, required: true, text: true, default: "" },
	data7: { unique: false, required: true, text: true, default: "" },
	data8: { unique: false, required: true, text: true, default: "" },
	data9: { unique: false, required: true, text: true, default: "" },
	data10: { unique: false, required: true, text: true, default: "" },
	data11: { unique: false, required: true, text: true, default: "" },
	data12: { unique: false, required: true, text: true, default: "" },
	data13: { unique: false, required: true, text: true, default: "" },
	data14: { unique: false, required: true, text: true, default: "" },
	data15: { unique: false, required: true, text: true, default: "" },
	data16: { unique: false, required: true, text: true, default: "" },
	data17: { unique: false, required: true, text: true, default: "" },
	data18: { unique: false, required: true, text: true, default: "" },
});

export const Buyout = model("Buyout", BuyoutSchema);
